{
 "title": "GlusterFS",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "label_values(gluster_up, job)" },
   {
    "name": "host",
    "label": "Host:",
    "query": "label_values(gluster_up, instance)"
   },
   {
    "name": "volume",
    "label": "volume",
    "query": "label_values(gluster_volume_status,volume)"
   }
  ]
 },
 "panels": [
  {
   "title": "GlusterFS Volume Size $volume",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "gluster_node_size_bytes_total{instance=\"$host\",volume=\"$volume\"}-gluster_node_size_free_bytes{instance=\"$host\",volume=\"$volume\"}",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Data growth",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "decbytes",
   "valueName": "diff",
   "targets": [
    {
     "expr": "gluster_node_size_bytes_total{instance=\"$host\",volume=\"$volume\"}-gluster_node_size_free_bytes{instance=\"$host\",volume=\"$volume\"}"
    }
   ]
  },
  {
   "title": "GlusterFS Inodes",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "gluster_node_inodes_total{instance=\"$host\",volume=\"$volume\"}-gluster_node_inodes_free{instance=\"$host\",volume=\"$volume\"}"
    }
   ]
  },
  {
   "title": "GlusterFS Heal files",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gluster_heal_info_files_count{instance=\"$host\",volume=\"$volume\"}",
     "legendFormat": "Heal Files count"
    }
   ]
  },
  {
   "title": "GlusterFS Brick Available",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gluster_brick_available{instance=\"$host\"}",
     "legendFormat": "$volume bricks"
    }
   ]
  }
 ]
}